"""
PR Builder for Hermes Agent Self-Evolution.

Auto-generates pull requests with metrics, diffs, and before/after comparisons
for evolved skill/tool/prompt variants.
"""

import subprocess
import json
import os
from typing import Dict, Any, Optional, List
from pathlib import Path
from dataclasses import dataclass, asdict
from datetime import datetime

from .constraints_impl import ValidationReport
from .benchmark_gate import BenchmarkReport
from .fitness import FitnessScore


@dataclass
class PRContent:
    """Content for a generated PR."""
    title: str
    body: str
    branch_name: str
    base_branch: str
    labels: List[str]
    files_changed: List[str]


class PRBuilder:
    """
    Builds PR content for evolved variants.
    
    Generates:
    - Descriptive title and body with metrics
    - Before/after comparison
    - Validation and benchmark results summary
    - Risk assessment
    """
    
    def __init__(
        self,
        hermes_agent_repo: Path,
        hermes_self_evo_repo: Path
    ):
        self.hermes_agent_repo = Path(hermes_agent_repo)
        self.hermes_self_evo_repo = Path(hermes_self_evo_repo)
    
    def build_skill_pr(
        self,
        skill_name: str,
        original_content: str,
        evolved_content: str,
        validation_report: ValidationReport,
        benchmark_report: Optional[BenchmarkReport] = None,
        fitness_comparison: Optional[Dict[str, Any]] = None,
        evolution_metadata: Optional[Dict[str, Any]] = None
    ) -> PRContent:
        """Build PR for an evolved skill."""
        
        # Generate branch name
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        branch_name = f"evolve/{skill_name}-{timestamp}"
        
        # Compute diff
        diff = self._generate_diff(skill_name, original_content, evolved_content)
        
        # Build PR body sections
        body_parts = []
        
        # Header
        body_parts.append(self._build_header(skill_name, evolution_metadata))
        
        # Summary metrics
        body_parts.append(self._build_metrics_summary(
            validation_report, benchmark_report, fitness_comparison
        ))
        
        # Validation results
        body_parts.append(self._build_validation_section(validation_report))
        
        # Benchmark results
        if benchmark_report:
            body_parts.append(self._build_benchmark_section(benchmark_report))
        
        # Fitness comparison
        if fitness_comparison:
            body_parts.append(self._build_fitness_section(fitness_comparison))
        
        # Diff
        body_parts.append(self._build_diff_section(diff))
        
        # Risk assessment
        body_parts.append(self._build_risk_assessment(validation_report, benchmark_report))
        
        # Footer
        body_parts.append(self._build_footer())
        
        body = "\n\n".join(body_parts)
        
        # Title
        improvement = ""
        if fitness_comparison and "percent_improvement" in fitness_comparison:
            pct = fitness_comparison["percent_improvement"] * 100
            improvement = f" (+{pct:.1f}%)"
        
        title = f"[Evolved] {skill_name}{improvement}"
        
        return PRContent(
            title=title,
            body=body,
            branch_name=branch_name,
            base_branch="main",
            labels=["evolved", "skill", "needs-review"],
            files_changed=[f"skills/{skill_name}.md"]
        )
    
    def _build_header(self, skill_name: str, metadata: Optional[Dict]) -> str:
        lines = [
            f"# Evolved Skill: `{skill_name}`",
            "",
            f"**Generated by:** Hermes Agent Self-Evolution",
            f"**Timestamp:** {datetime.now().isoformat()}",
        ]
        
        if metadata:
            lines.append(f"**Evolution Run:** {metadata.get('run_id', 'unknown')}")
            if 'iterations' in metadata:
                lines.append(f"**GEPA Iterations:** {metadata['iterations']}")
            if 'eval_source' in metadata:
                lines.append(f"**Eval Source:** {metadata['eval_source']}")
            if 'model' in metadata:
                lines.append(f"**Judge Model:** {metadata['model']}")
        
        lines.extend([
            "",
            "---",
            ""
        ])
        return "\n".join(lines)
    
    def _build_metrics_summary(
        self,
        validation: ValidationReport,
        benchmark: Optional[BenchmarkReport],
        fitness: Optional[Dict]
    ) -> str:
        lines = [
            "## 📊 Summary Metrics",
            "",
            "| Metric | Value | Status |",
            "|--------|-------|--------|",
        ]
        
        # Validation
        val_status = "✅ Pass" if validation.all_passed else f"❌ {len(validation.errors)} errors, ⚠️ {len(validation.warnings)} warnings"
        lines.append(f"| Validation | {val_status} | {'✅' if validation.all_passed else '❌'} |")
        
        # Benchmark
        if benchmark:
            bench_status = "✅ Pass" if benchmark.overall_status.value == "passed" else \
                          f"⚠️ {benchmark.overall_status.value}"
            lines.append(f"| Benchmarks | {bench_status} | {'✅' if benchmark.overall_status.value == 'passed' else '⚠️'} |")
        else:
            lines.append("| Benchmarks | Not Run | ⏭️ |")
        
        # Fitness
        if fitness and "percent_improvement" in fitness:
            pct = fitness["percent_improvement"] * 100
            fit_status = "✅ Improved" if pct >= 10 else "📈 Improved" if pct > 0 else "➖ No Change"
            lines.append(f"| Fitness Gain | {pct:+.1f}% | {'✅' if pct >= 10 else '📈'} |")
        
        # Overall
        overall_ok = validation.all_passed and (not benchmark or benchmark.overall_status.value in ["passed", "improved"])
        lines.append(f"| **Overall** | **{'✅ Ready for Review' if overall_ok else '❌ Needs Work'}** | {'✅' if overall_ok else '❌'} |")
        
        return "\n".join(lines)
    
    def _build_validation_section(self, report: ValidationReport) -> str:
        lines = [
            "## ✅ Validation Results",
            ""
        ]
        
        if report.all_passed:
            lines.append("All validation checks passed! ✅")
        else:
            lines.append(f"**{len(report.errors)} errors, {len(report.warnings)} warnings** found:")
        
        lines.append("")
        
        # Errors
        if report.errors:
            lines.append("### ❌ Errors (Blocking)")
            for err in report.errors:
                lines.append(f"- **{err.name}**: {err.message}")
                if err.details:
                    for k, v in err.details.items():
                        lines.append(f"  - {k}: {v}")
            lines.append("")
        
        # Warnings
        if report.warnings:
            lines.append("### ⚠️ Warnings")
            for warn in report.warnings:
                lines.append(f"- **{warn.name}**: {warn.message}")
            lines.append("")
        
        # Passed checks summary
        passed_count = len([r for r in report.results if r.passed])
        total_count = len(report.results)
        lines.append(f"*{passed_count}/{total_count} checks passed*")
        
        return "\n".join(lines)
    
    def _build_benchmark_section(self, report: BenchmarkReport) -> str:
        lines = [
            "## 🏁 Benchmark Results",
            ""
        ]
        
        status_emoji = {
            "passed": "✅",
            "improved": "📈",
            "stable": "➖",
            "regression": "📉",
            "failed": "❌",
            "skipped": "⏭️",
            "error": "💥"
        }
        
        for result in report.results:
            emoji = status_emoji.get(result.status.value, "❓")
            lines.append(f"### {emoji} {result.name}: {result.status.value.title()}")
            
            if result.score is not None:
                lines.append(f"- **Score:** {result.score:.2f}")
            if result.baseline_score is not None:
                diff = result.score - result.baseline_score
                pct = (diff / result.baseline_score * 100) if result.baseline_score != 0 else 0
                lines.append(f"- **Baseline:** {result.baseline_score:.2f} ({diff:+.2f}, {pct:+.1f}%)")
            lines.append(f"- **Duration:** {result.duration_seconds:.1f}s")
            if result.error:
                lines.append(f"- **Error:** {result.error}")
            lines.append("")
        
        # Overall
        overall_emoji = status_emoji.get(report.overall_status.value, "❓")
        lines.append(f"**Overall: {overall_emoji} {report.overall_status.value.title()}**")
        
        return "\n".join(lines)
    
    def _build_fitness_section(self, comparison: Dict[str, Any]) -> str:
        lines = [
            "## 🎯 Fitness Comparison (Baseline vs Evolved)",
            ""
        ]
        
        if "baseline" in comparison and "evolved" in comparison:
            base = comparison["baseline"]
            evo = comparison["evolved"]
            
            lines.extend([
                "| Metric | Baseline | Evolved | Change |",
                "|--------|----------|---------|--------|",
                f"| Mean Score | {base.get('mean', 0):.3f} | {evo.get('mean', 0):.3f} | {evo.get('mean', 0) - base.get('mean', 0):+.3f} |",
                f"| Pass Rate (≥0.7) | {base.get('pass_rate', 0):.1%} | {evo.get('pass_rate', 0):.1%} | {evo.get('pass_rate', 0) - base.get('pass_rate', 0):+.1%} |",
                f"| Std Dev | {base.get('std', 0):.3f} | {evo.get('std', 0):.3f} | {evo.get('std', 0) - base.get('std', 0):+.3f} |",
                f"| Sample Size | {base.get('n', 0)} | {evo.get('n', 0)} | — |",
                "",
            ])
        
        if "percent_improvement" in comparison:
            pct = comparison["percent_improvement"] * 100
            lines.append(f"**Overall Improvement: {pct:+.1f}%**")
            if comparison.get("statistically_significant"):
                lines.append("*Statistically significant* ✅")
            else:
                lines.append("*Not statistically significant* ⚠️")
        
        if "top_failures" in comparison.get("evolved", {}):
            lines.append("")
            lines.append("### Top Failures in Evolved Version")
            for failure, count in comparison["evolved"]["top_failures"][:5]:
                lines.append(f"- {failure}: {count} occurrences")
        
        return "\n".join(lines)
    
    def _build_diff_section(self, diff: str) -> str:
        lines = [
            "## 📝 Diff",
            "",
            "```diff",
            diff[:5000],  # Truncate if too long
            "```" if len(diff) <= 5000 else "... (truncated)",
            "",
        ]
        
        if len(diff) > 5000:
            lines.append("*Diff truncated. Full diff available in the branch.*")
        
        return "\n".join(lines)
    
    def _build_risk_assessment(
        self,
        validation: ValidationReport,
        benchmark: Optional[BenchmarkReport]
    ) -> str:
        lines = [
            "## ⚠️ Risk Assessment",
            ""
        ]
        
        risks = []
        
        # Validation risks
        if not validation.all_passed:
            risks.append(f"🔴 **Validation failures:** {len(validation.errors)} blocking errors")
        
        # Benchmark risks
        if benchmark:
            if benchmark.overall_status.value == "regression":
                risks.append("🔴 **Benchmark regression detected** - variant scores lower than baseline")
            elif benchmark.overall_status.value == "failed":
                risks.append("🟡 **Benchmark failures** - some benchmarks did not complete successfully")
            elif benchmark.overall_status.value == "improved":
                risks.append("🟢 **Benchmarks improved** - positive signal")
        
        # Size risk
        # (would need to check from validation details)
        
        if not risks:
            lines.append("🟢 **Low risk** - All checks pass, no regressions detected")
        else:
            for risk in risks:
                lines.append(f"- {risk}")
        
        lines.extend([
            "",
            "### Recommended Actions",
            "1. **Human review required** - All evolved variants need human approval before merge",
            "2. **Run additional manual tests** - Especially for the skill's primary use cases",
            "3. **A/B test in production** - Consider deploying to a subset of users first",
            "4. **Monitor post-merge** - Watch for any unexpected behavior changes",
        ])
        
        return "\n".join(lines)
    
    def _build_footer(self) -> str:
        return """---

*This PR was automatically generated by [Hermes Agent Self-Evolution](https://github.com/NousResearch/hermes-agent-self-evolution).*

**Review Checklist:**
- [ ] Skill purpose and trigger conditions preserved
- [ ] No hallucinated tool references
- [ ] Caching-compatible (no mid-conversation behavior changes)
- [ ] All tests pass
- [ ] Benchmarks hold or improve
- [ ] Changes are sensible to a human reviewer
- [ ] No malicious or unsafe instructions

**To test locally:**
```bash
# Checkout the branch
git fetch origin {branch_name}
git checkout {branch_name}

# Run the skill's test cases
hermes test skill {skill_name}

# Run full benchmark suite
python scripts/run_tblite_fast.py
```"""
    
    def _generate_diff(
        self, 
        skill_name: str, 
        original: str, 
        evolved: str
    ) -> str:
        """Generate unified diff between original and evolved content."""
        import difflib
        
        orig_lines = original.splitlines(keepends=True)
        evo_lines = evolved.splitlines(keepends=True)
        
        diff = difflib.unified_diff(
            orig_lines, evo_lines,
            fromfile=f"a/skills/{skill_name}.md",
            tofile=f"b/skills/{skill_name}.md",
            lineterm=""
        )
        
        return "\n".join(diff)
    
    def write_pr_files(self, pr: PRContent, output_dir: Path) -> None:
        """Write PR content to files for review/creation."""
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Write PR body
        (output_dir / "pr_body.md").write_text(pr.body)
        
        # Write metadata
        metadata = {
            "title": pr.title,
            "branch_name": pr.branch_name,
            "base_branch": pr.base_branch,
            "labels": pr.labels,
            "files_changed": pr.files_changed
        }
        (output_dir / "pr_metadata.json").write_text(json.dumps(metadata, indent=2))
        
        # Write diff
        (output_dir / "diff.patch").write_text(
            self._generate_diff(
                pr.files_changed[0].replace("skills/", "").replace(".md", ""),
                "",  # Would need original - this is just for file output
                ""
            )
        )


def create_skill_pr(
    hermes_agent_repo: Path,
    hermes_self_evo_repo: Path,
    skill_name: str,
    original_content: str,
    evolved_content: str,
    validation_report: ValidationReport,
    benchmark_report: Optional[BenchmarkReport] = None,
    fitness_comparison: Optional[Dict[str, Any]] = None,
    evolution_metadata: Optional[Dict[str, Any]] = None,
    output_dir: Optional[Path] = None
) -> PRContent:
    """Convenience function to build a skill PR."""
    builder = PRBuilder(hermes_agent_repo, hermes_self_evo_repo)
    pr = builder.build_skill_pr(
        skill_name=skill_name,
        original_content=original_content,
        evolved_content=evolved_content,
        validation_report=validation_report,
        benchmark_report=benchmark_report,
        fitness_comparison=fitness_comparison,
        evolution_metadata=evolution_metadata
    )
    
    if output_dir:
        builder.write_pr_files(pr, output_dir)
    
    return pr